### ISSUE TITLE
[bug] 快速滚动时会有空白

### ISSUE THREAD

**Issue by GitHdu** [falstack/vue-flow-render#7]
![image](https://user-images.githubusercontent.com/15519616/62522719-d7e72180-b864-11e9-9bb8-a4daf7ce38e8.png)

**Comment by falstack** [comment]
滚动结束的时候是否会渲染出来？
是哪个用例呢？

**Comment by GitHdu** [comment]
> 滚动结束的时候是否会渲染出来？
> 是哪个用例呢？

单列定高，不会，要稍微往回滚才能显示

**Comment by falstack** [comment]
一般这个情况增大 remind 就可以缓解

这个地方我也复现出来了几次，但复现概率比较低，还没找到稳定复现方法，先定性为 bug

**Comment by falstack** [comment]
fixed v1.0.1，做了一些无意义的优化导致的
